export const SET_REMINDER = 'SET_REMINDER'
export const UPDATE_REMINDER = 'UPDATE_REMINDER'
export const DELETE_REMINDER = 'DELETE_REMINDER'
export const CHECK_REMINDER = 'CHECK_REMINDER'


export const ADD_SUBTASK = 'ADD_SUBTASK'
export const UPDATE_SUBTASK = 'UPDATE_SUBTASK'
export const DELETE_SUBTASK = 'DELETE_SUBTASK'